Many to many
yosefHesham/vet_clin pull request #14
Opened 2023-01-20 23:09 UTC by yosefHesham

2023-01-20 23:45 UTC, Felix45 requested changes
Hi @yosefHesham, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif" />

 ## Highlights :heavy_check_mark: 
- [ ] Professional readme file :heavy_check_mark: 
- [ ] Descriptive pull request title and summary :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 23:45 UTC, Felix45 commented on data.sql
> +('Charmander','Feb 2, 2020',-11,false,0) ,
- [ Required ] Please consider adding `INSERT` statements in the `data.sql` file for the `vets` table as specified in the project requirements. Please see the screenshot below for more details on this.

## Project requirements
![Screenshot from 2023-01-21 02-31-57](https://user-images.githubusercontent.com/16392046/213823500-251f4b19-893b-4ecd-a1dd-346a39496dd1.png)

- [ Required ] Please consider adding `INSERT` statements in the `data.sql` file for the `specializations` table as specified in the project requirements. Please see the screenshot below for more details on this.

## Project requirements
![Screenshot from 2023-01-21 02-35-35](https://user-images.githubusercontent.com/16392046/213823789-f03bdf20-4e9b-406e-8032-ce3857c74aca.png)

- [ Required ] Please consider adding `INSERT` statements in the `data.sql` file for the `visits` table as specified in the project requirements. Please see the screenshot below for more details on this.

## Project requirements
![Screenshot from 2023-01-21 02-37-26](https://user-images.githubusercontent.com/16392046/213823934-7cfcf2b7-70ef-4cf4-91d6-1fd8e613798a.png)

2023-01-20 23:45 UTC, Felix45 commented on queries.sql
> +select count(*) from animals where escape_attempts = 0 ;
- [ Required ] Please consider adding `SQL QUERY` statements in the `queries.sql` file that answer the following questions as specified in the project requirements. Please see the screenshot below for more details on this.

## Project requirements
![Screenshot from 2023-01-21 02-42-52](https://user-images.githubusercontent.com/16392046/213824349-89a48322-d3e7-4b5e-bffe-2741d1de8442.png)

2023-01-21 00:26 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @yosefHesham, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You well to make the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 01:02 UTC, merged